import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Frontend Mentor - Interactive rating</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen items-center justify-center">
        <div className="h-[350px] w-[375px] rounded-3xl bg-veryDarkBlue">
          <img
            className="mt-5 ml-5 rounded-full bg-darkBlue p-3"
            src="./images/icon-star.svg"
            alt="start-icon"
          />
          <h1 className="m-5 bg-veryDarkBlue text-2xl text-lightGrey">
            How did we do?
          </h1>
          <p className="m-5 bg-veryDarkBlue text-sm text-lightGrey">
            Please let us know how we did with your support request. All
            feedback is appreciated to help us improve our offering!
          </p>
          <div className="flex justify-evenly rounded-full bg-veryDarkBlue">
            <button className="h-[50px] w-[50px] rounded-full bg-darkBlue">
              1
            </button>
            <button className="h-[50px] w-[50px] rounded-full bg-darkBlue">
              2
            </button>
            <button className=" h-[50px] w-[50px] rounded-full bg-darkBlue">
              3
            </button>
            <button className="h-[50px] w-[50px] rounded-full bg-darkBlue">
              4
            </button>
            <button className="h-[50px] w-[50px] rounded-full bg-darkBlue">
              5
            </button>
          </div>
          <div className="flex items-center justify-center bg-veryDarkBlue text-center">
            <button className=" m-5 w-full rounded-2xl bg-orange p-1 text-center text-white">
              Submit
            </button>
          </div>
        </div>
      </div>
    </>
  );
};

export default Home;
